Repository Leo-Brambilla/helpr-back-jfs5, pull requests merged in 2022-12, with the labels that each got.

#19 Reajustar a obrigatoriedade de nova senha ao atualizar usuário
  src/main/java/org/soulcodeacademy/helpr/domain/dto/UsuarioDTO.java
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
Labels: bug, enhancement

#20 trigger log_chamados
  src/main/java/org/soulcodeacademy/helpr/sql/tg_log_chamados.sql
Labels: enhancement

#21 Futuro cliente entidade e repository
  src/main/java/org/soulcodeacademy/helpr/HelprApplication.java
  src/main/java/org/soulcodeacademy/helpr/config/SecurityConfig.java
  src/main/java/org/soulcodeacademy/helpr/domain/Chamado.java
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCliente.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoClienteRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/AuthService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/java/org/soulcodeacademy/helpr/services/security/TokenFilter.java
  src/main/java/org/soulcodeacademy/helpr/services/security/TokenUtil.java
  src/main/java/org/soulcodeacademy/helpr/services/security/UsuarioSecurity.java
  src/main/java/org/soulcodeacademy/helpr/services/security/UsuarioSecurityService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#22 criado trigger bkp_cargos
  src/main/java/org/soulcodeacademy/helpr/sql/tg_bkp_cargos.sql
Labels: enhancement

#24 Criação bkp_usuarios
  src/main/java/org/soulcodeacademy/helpr/sql/tg_log_usuarios.sql
Labels: enhancement

#25 DTO do futuro cliente
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoClienteDTO.java
Labels: enhancement

#26 Popular service
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#27 criação bkp full usuarios
  src/main/java/org/soulcodeacademy/helpr/sql/tg_bkp_usuarios.sql
Labels: enhancement

#28 refatoracao dos métodos de leitura das entidades
  src/main/java/org/soulcodeacademy/helpr/services/CargoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
Labels: enhancement

#29 Futuro Cliente Service
  src/main/java/org/soulcodeacademy/helpr/services/FuturoClienteService.java
Labels: enhancement

#30 Arquivado chamado2
  src/main/java/org/soulcodeacademy/helpr/domain/enums/StatusChamado.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#37 Entidade e Repository FuturoCandidato
  src/main/java/org/soulcodeacademy/helpr/domain/FuturoCandidato.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Setor.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuturoCandidatoRepository.java
  src/main/resources/application-dev.properties
Labels: enhancement

#39 correção do controller do futuro cliente
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoClienteController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/FuturoClienteController.java
Labels: bug

#38 DTO de FuturoCandidato
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoCandidatoDTO.java
Labels: enhancement

#40 Task SERVICE FuturoCandidato
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Setor.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidadoService.java
  src/main/resources/application-dev.properties
Labels: enhancement

#41 Controller FuturoCandidato
  src/main/java/org/soulcodeacademy/helpr/controllers/FuturoCandidatoController.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/FuturoCandidatoDTO.java
  src/main/java/org/soulcodeacademy/helpr/services/FuturoCandidadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
Labels: enhancement

#42 remocao de comentarios
  src/main/java/org/soulcodeacademy/helpr/config/DevConfig.java
  src/main/java/org/soulcodeacademy/helpr/config/SecurityConfig.java
  src/main/java/org/soulcodeacademy/helpr/controllers/CargoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ChamadoController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/ClienteController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/FuncionarioController.java
  src/main/java/org/soulcodeacademy/helpr/controllers/errors/CustomErrorResponse.java
  src/main/java/org/soulcodeacademy/helpr/domain/Cargo.java
  src/main/java/org/soulcodeacademy/helpr/domain/Chamado.java
  src/main/java/org/soulcodeacademy/helpr/domain/Cliente.java
  src/main/java/org/soulcodeacademy/helpr/domain/Funcionario.java
  src/main/java/org/soulcodeacademy/helpr/domain/Usuario.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/CargoDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/ClienteDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/dto/UsuarioDTO.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/Perfil.java
  src/main/java/org/soulcodeacademy/helpr/domain/enums/StatusChamado.java
  src/main/java/org/soulcodeacademy/helpr/repositories/CargoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/ChamadoRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/ClienteRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/FuncionarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/repositories/UsuarioRepository.java
  src/main/java/org/soulcodeacademy/helpr/services/AuthService.java
  src/main/java/org/soulcodeacademy/helpr/services/CargoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ChamadoService.java
  src/main/java/org/soulcodeacademy/helpr/services/ClienteService.java
  src/main/java/org/soulcodeacademy/helpr/services/FuncionarioService.java
  src/main/java/org/soulcodeacademy/helpr/services/PopulateService.java
  src/main/java/org/soulcodeacademy/helpr/services/errors/ParametrosInsuficientesError.java
  src/main/java/org/soulcodeacademy/helpr/services/errors/RecursoNaoEncontradoError.java
  src/main/java/org/soulcodeacademy/helpr/services/security/TokenFilter.java
  src/main/java/org/soulcodeacademy/helpr/services/security/TokenUtil.java
  src/main/java/org/soulcodeacademy/helpr/services/security/UsuarioSecurity.java
  src/main/java/org/soulcodeacademy/helpr/services/security/UsuarioSecurityService.java
  src/main/resources/application-dev.properties
Labels: enhancement
